name: Generate Tutorial

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-tutorial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate tutorial
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: scripts/generate_tutorial.py

      - name: Commit and push docs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/tutorial
          git commit -m "chore: update tutorial" || echo "No changes"
          git push 